// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://hdhjoegjghurgoujjbkj.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaGpvZWdqZ2h1cmdvdWpqYmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExMTg1OTksImV4cCI6MjA5NjY5NDU5OX0.7kco3LAxWdq_flbTtTraTFLxs5OlXDQRbLFQ2Wk7Pv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});